### ISSUE TITLE
文件乱码问题及注释中若干拼写错误

### ISSUE THREAD

**Issue by imliuruiqi** [Ehco1996/Python-crawler#3]
诸如在百度贴吧爬虫中，Windows系统上似乎在存取文件时需要设置：`encoding=‘utf-8’` ，否则的话会导致文件乱码。
此外在代码第二十行
`# r.endcodding = r.apparent_endconding`
中有明显的拼写错误。

**Comment by Ehco1996** [comment]
很抱歉，已经修改好了

代码里可能有很多很多的错别字
但是已经没有时间去一点一点修复了

如果可能的话 欢迎 PR
