### ISSUE TITLE
知乎专栏  从零开始写Python爬虫 --- 1.5 爬虫实践： 获取百度贴吧内容 发现问题

### ISSUE THREAD

**Issue by Mr-Liu-CUG** [Ehco1996/Python-crawler#8]
win10，pycharm，python3.5
litags = soup.find_all('li', attrs={'class': ' j_thread_list clearfix'})  该行代码返回的是空列表，无法爬取到内容。
***********************************求解惑***********************************
运行没有报错。
下面附上我的代码

import requests
from bs4 import BeautifulSoup
import time

def get_html(url):
    try:
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        r.encoding = 'utf-8'  # 爬取其他未知编码网页用r.encoding = r.apparent_encoding
        return r.text
    except:
        return 'ERROR'

def get_content(url):
    '''分析贴吧的网页内容，整理信息，保存在列表中'''
    # 初始化列表，保存帖子所有信息
    comments = []
    # 首先，下载需要爬取的网页
    html = get_html(url)
    soup = BeautifulSoup(html, 'lxml')

    # 找到所有具有' j_thread_list clearfix'属性的Li标签，返回列表类型
    #litags = soup.find_all('li', attrs={'class': ' j_thread_list clearfix'})
    litags = soup.find_all('li', attrs={'class': ' j_thread_list clearfix'})
    print(litags)#litags内容为[]
    print('**************')#该行以下没有运行
    # 通过循环找到每个帖子里面需要的信息
    for li in litags:
        # 初始化一个字典来储存文章信息
        comment = {}
        print('**************')
        try:
            # 开始筛选信息，并且保存到字典中
            comment['title'] = li.find('a', attrs={'class': 'j_th_tit '}).text.strip()
            comment['link'] = "http://tieba.baidu.com/" + li.find('a', attrs={'class': 'j_th_tit '})['href']
            comment['name'] = li.find('span', attrs={'class': "tb_icon_author "}).text.strip()
            comment['time'] = li.find('span', attrs={'class': 'pull-right is_show_creat_time'}).text.strip()
            comment['replayNum'] = li.find('span', attrs={'class': "threadlist_rep_num center_text"}).text.strip()
            comments.append(comment)
            print('**************')

        except:
            print('出了点小问题')

    return comments

def out2file(dict):
    """将爬取到的内容写入本地文件，保存到ttbt.txt"""
    with open('TTBT.txt', 'a+') as f:
        for comment in dict:
            f.write('正在写入内容...\n')
            f.write('标题: {} \t 链接: {} \t 发帖人: {} \t 发帖时间: {} \t 回复数量: {} '.format(comment['title'],
                                                                                  comment['link'], comment['name'],
                                                                                  comment['time'],
                                                                                  comment['replayNum']))

        print("当前页面爬取完成！")

def main(base_url, deep):
    url_list = []

    # 将所有需要爬取的页面url存入列表
    for i in range(0, deep):
        url_list.append(base_url + "&pn=" + str(50 * i))

    print("所有网页已经下载到本地！开始筛选信息...")

    # 循环写入所有数据
    for url in url_list:
        content = get_content(url)
        print(content)  #该行有运行，打印[]
        out2file(content)
    print("所有信息都已经保存完毕！")

base_url = 'http://tieba.baidu.com/f?kw=%E7%94%9F%E6%B4%BB%E5%A4%A7%E7%88%86%E7%82%B8&ie=utf-8'
deep = 1  # 需要爬取的页面数
# if __name__ == '__main__':
main(base_url, deep)

**Comment by Mr-Liu-CUG** [comment]
``import requests
from bs4 import BeautifulSoup
import time


def get_html(url):
    try:
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        r.encoding = 'utf-8'  # 爬取其他未知编码网页用r.encoding = r.apparent_encoding
        return r.text
    except:
        return 'ERROR'


def get_content(url):
    '''分析贴吧的网页内容，整理信息，保存在列表中'''
    # 初始化列表，保存帖子所有信息
    comments = []
    # 首先，下载需要爬取的网页
    html = get_html(url)
    soup = BeautifulSoup(html, 'lxml')

    # 找到所有具有' j_thread_list clearfix'属性的Li标签，返回列表类型
    #litags = soup.find_all('li', attrs={'class': ' j_thread_list clearfix'})
    litags = soup.find_all('li', attrs={'class': ' j_thread_list clearfix'})
    print(litags)#litags内容为[]
    print('**************')#该行以下没有运行
    # 通过循环找到每个帖子里面需要的信息
    for li in litags:
        # 初始化一个字典来储存文章信息
        comment = {}
        print('**************')
        try:
            # 开始筛选信息，并且保存到字典中
            comment['title'] = li.find('a', attrs={'class': 'j_th_tit '}).text.strip()
            comment['link'] = "http://tieba.baidu.com/" + li.find('a', attrs={'class': 'j_th_tit '})['href']
            comment['name'] = li.find('span', attrs={'class': "tb_icon_author "}).text.strip()
            comment['time'] = li.find('span', attrs={'class': 'pull-right is_show_creat_time'}).text.strip()
            comment['replayNum'] = li.find('span', attrs={'class': "threadlist_rep_num center_text"}).text.strip()
            comments.append(comment)
            print('**************')

        except:
            print('出了点小问题')

    return comments


def out2file(dict):
    """将爬取到的内容写入本地文件，保存到ttbt.txt"""
    with open('TTBT.txt', 'a+') as f:
        for comment in dict:
            f.write('正在写入内容...\n')
            f.write('标题: {} \t 链接: {} \t 发帖人: {} \t 发帖时间: {} \t 回复数量: {} '.format(comment['title'],
                                                                                  comment['link'], comment['name'],
                                                                                  comment['time'],
                                                                                  comment['replayNum']))

        print("当前页面爬取完成！")


def main(base_url, deep):
    url_list = []

    # 将所有需要爬取的页面url存入列表
    for i in range(0, deep):
        url_list.append(base_url + "&pn=" + str(50 * i))

    print("所有网页已经下载到本地！开始筛选信息...")

    # 循环写入所有数据
    for url in url_list:
        content = get_content(url)
        print(content)  #该行有运行，打印[]
        out2file(content)
    print("所有信息都已经保存完毕！")


base_url = 'http://tieba.baidu.com/f?kw=%E7%94%9F%E6%B4%BB%E5%A4%A7%E7%88%86%E7%82%B8&ie=utf-8'
deep = 1  # 需要爬取的页面数
# if __name__ == '__main__':
main(base_url, deep)

**Comment by Ehco1996** [comment]
应该是网页结构变动啦，所以拿到的信息是空的
可以研究一下，做一些修改，毕竟这些都是三年前的代码啦
